woowacourse-teams/2021-darass

backend/src/main/java/com/darass/darass/comment/domain/Comment.java, backend/src/main/java/com/darass/darass/comment/repository/CommentRepository.java, backend/src/main/java/com/darass/darass/project/domain/Project.java, backend/src/main/java/com/darass/darass/project/repository/ProjectRepository.java, backend/src/main/java/com/darass/darass/user/domain/GuestUser.java, backend/src/main/java/com/darass/darass/user/domain/OAuthPlatform.java, backend/src/main/java/com/darass/darass/user/domain/SocialLoginUser.java, backend/src/main/java/com/darass/darass/user/domain/User.java, backend/src/main/java/com/darass/darass/user/repository/UserRepository.java
User, Project, Comment 엔티티 테이블 매핑
=>   [BE] 테이블 매핑

backend/src/main/java/com/darass/darass/auth/oauth/infrastructure/LoginInterceptor.java, backend/src/main/java/com/darass/darass/comment/service/CommentService.java, backend/src/main/java/com/darass/darass/project/controller/ProjectController.java, backend/src/main/java/com/darass/darass/project/controller/dto/ProjectRequest.java, backend/src/main/java/com/darass/darass/project/controller/dto/ProjectResponse.java, backend/src/main/java/com/darass/darass/project/domain/Project.java, backend/src/main/java/com/darass/darass/project/exception/NotFoundException.java, backend/src/main/java/com/darass/darass/project/repository/ProjectRepository.java, backend/src/main/java/com/darass/darass/project/service/ProjectService.java
=> [BE] 프로젝트 api 구현

backend/src/main/java/com/darass/darass/auth/oauth/AuthControllerAdvice.java, backend/src/main/java/com/darass/darass/auth/oauth/AuthenticationPrincipalConfig.java, backend/src/main/java/com/darass/darass/auth/oauth/controller/AuthenticationPrincipalArgumentResolver.java, backend/src/main/java/com/darass/darass/auth/oauth/controller/OAuthController.java, backend/src/main/java/com/darass/darass/auth/oauth/domain/AuthenticationPrincipal.java, backend/src/main/java/com/darass/darass/auth/oauth/infrastructure/LoginInterceptor.java, backend/src/main/java/com/darass/darass/auth/oauth/service/AuthService.java, backend/src/main/java/com/darass/darass/auth/oauth/service/OAuthService.java, backend/src/main/java/com/darass/darass/comment/controller/CommentController.java, backend/src/main/java/com/darass/darass/comment/service/CommentService.java, backend/src/main/java/com/darass/darass/user/domain/GuestUser.java, backend/src/main/java/com/darass/darass/user/domain/SocialLoginUser.java, backend/src/main/java/com/darass/darass/user/domain/User.java
=> [BE] 댓글 api에 어떠한 유저가 댓글을 달았는지 판단하는 기능 구현

backend/build.gradle, backend/src/test/java/com/darass/darass/AcceptanceTest.java
=> [BE] 환경별 profile 설정

frontend/manage/tsconfig.json
=> [FE] 관리자 페이지 tsconfig 오타 수정 (#50)

frontend/reply-module/src/components/atoms/CommentOption/styles.ts, frontend/reply-module/src/components/atoms/SubmitButton/styles.ts
GlobalStyles의 button에 주어진 스타일과 동일한 스타일 선언 제거
=> [FE] GlobalStyle과 중복된 button 스타일 제거 (#52)

backend/src/docs/asciidoc/api/v1/comments.adoc, backend/src/docs/asciidoc/index.adoc, backend/src/test/java/com/darass/darass/comment/acceptance/CommentAcceptanceTest.java
Close #92 
+ 댓글 api restdocs 작성
=> [BE] 댓글 api Rest docs 적용 

backend/build.gradle, backend/src/docs/asciidoc/api/v1/users.adoc, backend/src/docs/asciidoc/index.adoc, backend/src/main/java/com/darass/darass/comment/controller/dto/CommentResponse.java, backend/src/main/java/com/darass/darass/comment/controller/dto/UserResponse.java, backend/src/main/java/com/darass/darass/comment/domain/Comment.java, backend/src/main/java/com/darass/darass/exception/ExceptionWithMessageAndCode.java, backend/src/main/java/com/darass/darass/project/service/ProjectService.java, backend/src/main/java/com/darass/darass/user/controller/UserController.java, backend/src/main/java/com/darass/darass/user/controller/dto/UserUpdateRequest.java, backend/src/main/java/com/darass/darass/user/domain/GuestUser.java, backend/src/main/java/com/darass/darass/user/domain/SocialLoginUser.java, backend/src/main/java/com/darass/darass/user/domain/User.java, backend/src/main/java/com/darass/darass/user/repository/UserRepository.java, backend/src/main/java/com/darass/darass/user/service/UserService.java, backend/src/test/java/com/darass/darass/comment/acceptance/CommentAcceptanceTest.java, backend/src/test/java/com/darass/darass/common/domain/BaseTimeEntityTest.java, backend/src/test/java/com/darass/darass/project/acceptance/ProjectAcceptanceTest.java, backend/src/test/java/com/darass/darass/user/controller/UserAcceptanceTest.java, backend/src/test/java/com/darass/darass/user/domain/GuestUserTest.java, backend/src/test/java/com/darass/darass/user/domain/SocialLoginUserTest.java, backend/src/test/java/com/darass/darass/user/service/UserServiceTest.java
- 유저 조회, 유저 닉네임 수정, 유저 삭제 api 구현완료
- rest docs 작성 완료 
- 인수 테스트, 서비스 통합 테스트 구현 완료 
- jackson으로 `LocalDateTime` 필드를 가지고 있는 DTO를 변환하지 못하는 이슈가 있었음
- jackson에서 `LocalDateTime` 필드변환을 지원하지 않기 때문
- jackson-datatype-jsr310 의존성을 추가하고, DTO의 `LocalDateTime` 필드에 애노테이션을 붙여줘서 해결 
- 다음링크를 참고함 https://m.blog.naver.com/writer0713/221615276956
=> [BE] 유저 정보 조회 api를 만든다. (#86)

backend/src/main/java/com/darass/darass/comment/controller/CommentController.java, backend/src/main/java/com/darass/darass/comment/domain/Comment.java, backend/src/main/java/com/darass/darass/comment/domain/Comments.java, backend/src/main/java/com/darass/darass/comment/service/CommentService.java, backend/src/main/java/com/darass/darass/project/domain/Project.java, backend/src/test/java/com/darass/darass/auth/oauth/api/domain/UserInfoProviderTest.java, backend/src/test/java/com/darass/darass/auth/oauth/infrastructure/JwtTokenProviderTest.java, backend/src/test/java/com/darass/darass/auth/oauth/service/OAuthServiceTest.java, backend/src/test/java/com/darass/darass/comment/acceptance/CommentAcceptanceTest.java, backend/src/test/java/com/darass/darass/comment/domain/CommentTest.java, backend/src/test/java/com/darass/darass/comment/domain/CommentsTest.java, backend/src/test/java/com/darass/darass/project/domain/ProjectTest.java
=> [BE] URL과 프로젝트 키를 기준으로 댓글을 조회한다.(#112)

backend/src/docs/asciidoc/api/v1/projects.adoc, backend/src/main/java/com/darass/darass/project/controller/ProjectController.java, backend/src/main/java/com/darass/darass/project/controller/dto/ProjectResponse.java, backend/src/main/java/com/darass/darass/project/domain/Project.java, backend/src/main/java/com/darass/darass/project/service/ProjectService.java, backend/src/main/java/com/darass/darass/user/domain/User.java, backend/src/test/java/com/darass/darass/project/acceptance/ProjectAcceptanceTest.java, backend/src/test/java/com/darass/darass/user/controller/UserAcceptanceTest.java
- 프로젝트 키를 주면, 프로젝트의 User id를 반환해주는 api 구현 (프론트 요청 사항)
=> [BE] 프로젝트 키를 통해 프로젝트의 주인 아이디를 리턴한다. (#129)

backend/src/main/java/com/darass/darass/auth/oauth/controller/AuthenticationPrincipalArgumentResolver.java, backend/src/main/java/com/darass/darass/comment/controller/CommentController.java, backend/src/main/java/com/darass/darass/comment/controller/dto/CommentCreateRequest.java, backend/src/main/java/com/darass/darass/comment/controller/dto/CommentDeleteRequest.java, backend/src/main/java/com/darass/darass/exception/ExceptionWithMessageAndCode.java, backend/src/main/java/com/darass/darass/exception/controller/ControllerAdvice.java, backend/src/main/java/com/darass/darass/exception/httpbasicexception/BadRequestException.java, backend/src/main/java/com/darass/darass/project/service/ProjectService.java, backend/src/test/java/com/darass/darass/comment/acceptance/CommentAcceptanceTest.java, backend/src/test/java/com/darass/darass/exception/controller/ControllerAdviceTest.java, backend/src/test/java/com/darass/darass/project/service/ProjectServiceTest.java
- ControllerAdvice 클래스 리팩터링과 테스트 코드 작성을 했습니다.
- handleConflictException 메서드에 대한 테스트 코드는 작성하지 않았는데, 프로젝트 키 생성관련해서 논의를 했으면 좋겠습니다!
- 전체적으로 테스트 커버리지가 올랐습니다. 논의해서 jacoco 커버리지 설정을 다시 해줘도 될 거 같습니다.
=> [BE] 예외 관련 테스트 코드를 작성한다. (#169)

backend/src/main/java/com/darass/darass/common/JpaAuditingConfiguration.java
=> [BE] 서버 시간 한국으로 설정 (#180)

backend/src/docs/asciidoc/api/v1/projects.adoc, backend/src/main/java/com/darass/darass/exception/ExceptionWithMessageAndCode.java, backend/src/main/java/com/darass/darass/project/domain/Project.java, backend/src/main/java/com/darass/darass/project/repository/ProjectRepository.java, backend/src/main/java/com/darass/darass/project/service/ProjectService.java, backend/src/test/java/com/darass/darass/project/acceptance/ProjectAcceptanceTest.java, backend/src/test/java/com/darass/darass/project/service/ProjectServiceTest.java
- 특정 사용자의 프로젝트 이름을 중복 사용하지 못하게 수정
- REST DOCS 컨벤션에 맞게 파일명 수정
=> [BE] 특정 사용자의 프로젝트 이름을 중복 사용하지 못하게 수정 (#218)

frontend/manage/package.json, frontend/manage/src/components/templates/ScriptPublishing/index.tsx, frontend/manage/src/components/templates/ScriptPublishing/styles.ts, frontend/manage/src/constants/domain.ts, frontend/manage/src/constants/guideFile.ts, frontend/manage/src/constants/index.ts, frontend/manage/src/types/type.d.ts
=> [FE][관리자 페이지] script 코드 상세 가이드 추가 (#242)

backend/src/main/resources/logback-access.xml, backend/src/main/resources/logback.xml
- 로깅이 시간 단위로 파일이 분리되지 않는 버그 수정
- 로깅 형태를 가독성 있게 수정
close #252
=> [BE] 로깅 에러 수정 (#252)

frontend/reply-module/src/__test__/intergration/guestUserComment.test.tsx, frontend/reply-module/src/components/atoms/CommentOption/index.tsx, frontend/reply-module/src/components/atoms/CommentOption/styles.ts, frontend/reply-module/src/components/molecules/Comment/index.tsx, frontend/reply-module/src/components/organisms/CommentList/index.tsx, frontend/reply-module/src/components/pages/CommentPage/index.tsx, frontend/reply-module/src/components/templates/CommentArea/index.tsx, frontend/reply-module/src/constants/api.ts, frontend/reply-module/src/constants/reactQueryKey.ts, frontend/reply-module/src/hooks/index.ts, frontend/reply-module/src/hooks/useGetAllComments.ts, frontend/reply-module/src/hooks/useProject.ts, frontend/reply-module/src/styles/css.ts, frontend/reply-module/src/types/comment.ts, frontend/reply-module/src/types/project.ts
=> [FE][댓글모듈] 관리자 유저 댓글 관리 기능 추가 (#177)

frontend/reply-module/src/__test__/fixture/comments.ts, frontend/reply-module/src/__test__/fixture/project.ts, frontend/reply-module/src/__test__/intergration/adminUserComment.test.tsx, frontend/reply-module/src/components/atoms/CommentOption/index.tsx
=> [FE][댓글모듈] 관리자 유저에 대한 테스트 코드를 작성한다. (#176)

frontend/reply-module/src/__test__/fixture/comments.ts, frontend/reply-module/src/__test__/fixture/project.ts, frontend/reply-module/src/__test__/intergration/adminUserComment.test.tsx, frontend/reply-module/src/__test__/intergration/socialLoginUserComment.test.tsx, frontend/reply-module/src/components/atoms/CommentOption/index.tsx, frontend/reply-module/src/components/atoms/CommentTextBox/index.tsx, frontend/reply-module/src/components/molecules/Comment/index.tsx, frontend/reply-module/src/components/organisms/CommentInput/index.tsx, frontend/reply-module/src/components/organisms/CommentList/index.tsx
=> [FE][댓글모듈] 로그인 회원 댓글 CRUD에 대해 테스트 코드를 작성한다. (#174)

.github/workflows/pr_checker.yml, frontend/manage/src/__test__/fixture/project.ts, frontend/manage/src/__test__/integration/myProjectPage.test.tsx, frontend/manage/src/components/atoms/Buttons/ProjectButton/index.tsx, frontend/manage/src/components/templates/MyProject/index.tsx
- 프로젝트가 하나도 없는 경우 프로젝트 추가 안내 메시지를 보여준다.
- 프로젝트가 존재하는 경우 프로젝트의 이름을 보여준다.
- 프로젝트 추가 버튼을 클릭하면 프로젝트 생성 페이지로 이동한다.
- 프로젝트 버튼을 클릭하면 프로젝트 스크립트 가이드 페이지로 이동한다.
=> [FE][관리자 페이지] MyProject 페이지의 테스트 코드를 작성 (#172)

frontend/manage/src/components/atoms/Avatar/index.tsx, frontend/manage/src/components/atoms/UserOption/index.tsx, frontend/manage/src/components/atoms/UserOption/styles.ts, frontend/manage/src/components/molecules/UserAvatarOption/index.tsx, frontend/manage/src/components/molecules/UserAvatarOption/styles.ts, frontend/manage/src/components/pages/MyProject/index.tsx, frontend/manage/src/styles/palette.ts
- 마우스 호버 UI 변경
- 다른 영역 클릭 시 옵션 닫힘 기능 추가
=> [FE][관리자 페이지] userOption 컴포넌트 인터랙션 추가 (#288)

backend/src/docs/asciidoc/api/v1/projects.adoc, backend/src/main/java/com/darass/darass/project/controller/ProjectController.java, backend/src/main/java/com/darass/darass/project/domain/Project.java, backend/src/main/java/com/darass/darass/project/dto/ProjectCreateRequest.java, backend/src/main/java/com/darass/darass/project/dto/ProjectResponse.java, backend/src/main/java/com/darass/darass/project/dto/ProjectUpdateRequest.java, backend/src/main/java/com/darass/darass/project/service/ProjectService.java, backend/src/test/java/com/darass/darass/AcceptanceTest.java, backend/src/test/java/com/darass/darass/project/acceptance/ProjectAcceptanceTest.java, backend/src/test/java/com/darass/darass/project/domain/ProjectTest.java, backend/src/test/java/com/darass/darass/project/service/ProjectServiceTest.java
구현 내용
- 프로젝트 설명(content) 필드 추가 
- 프로젝트 수정 api 구현 
- 인수테스트, 통합테스트, 도메인 테스트 수정 및 추가
- rest doc 적용 완료 
close #275
=> [BE] 프로젝트 상세설명 추가, 수정기능 (#275)

backend/src/main/java/com/darass/darass/comment/domain/Comment.java, backend/src/main/java/com/darass/darass/comment/domain/CommentLike.java, backend/src/main/java/com/darass/darass/project/domain/Project.java, backend/src/main/java/com/darass/darass/user/domain/User.java, backend/src/test/java/com/darass/darass/project/domain/ProjectTest.java, backend/src/test/java/com/darass/darass/project/service/ProjectServiceTest.java
- 기존에 UserServiceTest에서 deleteById 테스트는 왜 문제 없이 통과했을까요?..
- @JoinColum를 갖는 필드에 @OnDelete(action = OnDeleteAction.CASCADE)를 추가해서 카스케이스 설정하는 방식으로 모두 바꿔봤습니다!
=> [BE] 유저가 삭제되지 않는 버그 (#325)

frontend/deploy-script/src/index.js, frontend/reply-module/src/components/molecules/Comment/index.tsx, frontend/reply-module/src/hooks/useContentEditable.ts, frontend/reply-module/src/styles/GlobalStyles.ts
=> [FE][댓글모듈] 부모 프레임에 스크롤이 생기지 않도록 변경 (#331)

frontend/deploy-script/src/createIframe.js, frontend/deploy-script/src/index.js, frontend/reply-module/src/App.tsx, frontend/reply-module/src/components/atoms/Modal/index.tsx, frontend/reply-module/src/components/molecules/LikingUsersModal/index.tsx, frontend/reply-module/src/index.tsx
=> [FE][댓글모듈] 부모 프레임 클릭 시에도 모달이 닫히는 기능 추가 (#330)

frontend/deploy-script/.gitignore, frontend/deploy-script/src/common.js, frontend/deploy-script/src/constants.js, frontend/deploy-script/src/createIframe.js, frontend/deploy-script/src/getReplyModuleURL.js, frontend/deploy-script/src/index.js, frontend/deploy-script/src/style.js, frontend/reply-module/package.json, frontend/reply-module/public/modal.html, frontend/reply-module/src/App.tsx, frontend/reply-module/src/Modal.tsx, frontend/reply-module/src/components/atoms/Modal/index.tsx, frontend/reply-module/src/components/atoms/Modal/styles.ts, frontend/reply-module/src/components/molecules/Comment/index.tsx, frontend/reply-module/src/components/molecules/LikingUsersModal/index.tsx, frontend/reply-module/src/components/pages/CommentArea/index.tsx, frontend/reply-module/src/constants/postMessageType.ts, frontend/reply-module/src/hooks/useContentEditable.ts, frontend/reply-module/src/index.tsx, frontend/reply-module/src/modal.tsx, frontend/reply-module/src/utils/iframePostMessage.ts, frontend/reply-module/src/utils/postMessage.ts, frontend/reply-module/webpack.config.js
=> [FE][댓글모듈] 모달을 부모의 뷰포트 가운데에 띄우는 기능 추가 (#337)

backend/src/main/java/com/darass/darass/comment/domain/CommentStat.java, backend/src/main/java/com/darass/darass/comment/dto/CommentStatResponse.java, backend/src/main/java/com/darass/darass/comment/repository/CommentCountStrategy.java, backend/src/main/java/com/darass/darass/comment/repository/CommentCountStrategyByDaily.java, backend/src/main/java/com/darass/darass/comment/repository/CommentCountStrategyByHourly.java, backend/src/main/java/com/darass/darass/comment/repository/CommentCountStrategyByMonthly.java, backend/src/main/java/com/darass/darass/comment/service/CommentService.java, backend/src/test/java/com/darass/darass/comment/acceptance/CommentAcceptanceTest.java, backend/src/test/java/com/darass/darass/comment/service/CommentServiceTest.java
outer 로직을 간편하게 개편했고, 마지막 일과 마지막 달 따로 분기 처리했습니다.
=> [BE] 통계 마지막일과 마지막달 0개 처리 (#443)

backend/src/main/resources/logback-spring.xml
develop 서버에서도 콘솔창에 로깅할 수 있도록 설정 추가했고, 슬랙으로 알람까지 오도록 설정했습니다~!
=> [BE] develop 서버에도 에러 로깅할 수 있도록 장치 만들기 (#432) 

frontend/manage/src/components/organisms/ErrorNotice/styles.ts, frontend/reply-module/.gitignore, frontend/reply-module/package.json, frontend/reply-module/src/__test__/intergration/adminUserComment.test.tsx, frontend/reply-module/src/__test__/intergration/guestUserComment.test.tsx, frontend/reply-module/src/__test__/intergration/socialLoginUserComment.test.tsx, frontend/reply-module/src/components/atoms/CommentTextBox/styles.ts, frontend/reply-module/src/components/molecules/Comment/index.tsx, frontend/reply-module/src/components/organisms/CommentInput/index.tsx, frontend/reply-module/src/components/organisms/CommentInput/styles.ts, frontend/reply-module/src/components/organisms/CommentList/index.tsx, frontend/reply-module/src/components/organisms/ErrorNotice/ErrorNotice.stories.tsx, frontend/reply-module/src/components/organisms/ErrorNotice/index.tsx, frontend/reply-module/src/components/organisms/ErrorNotice/styles.tsx, frontend/reply-module/src/components/pages/CommentArea/index.tsx, frontend/reply-module/src/components/pages/ErrorPage/index.tsx, frontend/reply-module/src/components/pages/ErrorPage/styles.tsx, frontend/reply-module/src/constants/comment.ts, frontend/reply-module/src/hooks/useContentEditable.ts, frontend/reply-module/src/hooks/useCreateComment.ts, frontend/reply-module/src/hooks/useDeleteComment.ts, frontend/reply-module/src/hooks/useEditComment.ts, frontend/reply-module/src/hooks/useLikeComment.ts, frontend/reply-module/src/index.tsx, frontend/reply-module/src/styles/constants.ts, frontend/reply-module/webpack.config.js, frontend/reply-module/yarn.lock
- (댓글 모듈) **작성자를 운영자로 변경**
- (댓글 모듈) **에러바운더리 추가**
- (댓글 모듈) **센트리 추가**
- (댓글 모듈) **댓글 글자 수 카운팅 및 입력 제한**
- (댓글 모듈) **삭제된 댓글에 대댓글이나 좋아요를 누르면 404가 뜬다. 알러트 메시지 띄우기**
=> [FE][댓글모듈] QA 피드백 반영 (#457)

backend/src/main/java/com/darass/darass/auth/oauth/controller/argumentresolver/RequiredLoginArgumentResolver.java, backend/src/main/java/com/darass/darass/user/domain/SocialLoginUser.java
=> 리프레쉬 토큰이 삭제된 후, 리프레쉬 토큰 검사 기능 수행시 발생하는 NPE 예외를 수정한다. 

backend/src/main/java/com/darass/darass/auth/oauth/controller/argumentresolver/RequiredLoginArgumentResolver.java, backend/src/main/java/com/darass/darass/user/domain/SocialLoginUser.java
=> 리프레쉬 토큰이 삭제된 후, 리프레쉬 토큰 검사 기능 수행시 발생하는 NPE 예외를 수정한다.

backend/build.gradle, backend/src/main/java/com/darass/darass/config/WebConfig.java, backend/src/main/java/com/darass/darass/config/datasource/CircularList.java, backend/src/main/java/com/darass/darass/config/datasource/CustomDataSource.java, backend/src/main/java/com/darass/darass/config/datasource/CustomDataSourceConfig.java, backend/src/main/java/com/darass/darass/config/datasource/ReplicationRoutingDataSource.java
밑의 링크들을 참고해서 레플리케이션 구현해봤습니다~!!
[[DB, Spring] Replication 적용하기](https://velog.io/@max9106/DB-Spring-Replication)
[Spring Boot + JPA DB Replication 설정하기](https://velog.io/@kingcjy/Spring-Boot-JPA-DB-Replication-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0)
[Spring Boot DB Replication](https://blog.naver.com/PostView.nhn?isHttpsRedirect=true&blogId=opzyra&logNo=221510226411)
=> DB 레플리케이션 적용

backend/build.gradle, backend/src/main/java/com/darass/darass/TestDataLoader.java
- develop 환경에서만 테스트 데이터를 저장하게 함 
- user, project, comment 데이터가 1개이상 있다면 테스트 데이터 저장 로직은 돌아가지 않는다. 
closes: #582
=> 테스트용 데이터를 DB에 추가한다.

backend/build.gradle, backend/src/main/java/com/darass/darass/comment/dto/CommentResponse.java, backend/src/main/java/com/darass/darass/comment/dto/SubCommentResponse.java, backend/src/main/java/com/darass/darass/comment/service/CommentService.java, backend/src/main/java/com/darass/darass/common/domain/BaseTimeEntity.java, backend/src/main/java/com/darass/darass/config/CacheConfig.java, backend/src/main/java/com/darass/darass/user/dto/UserResponse.java
=> Spring Data Cache를 적용한다.

backend/build.gradle, backend/src/main/java/com/darass/darass/comment/controller/CommentController.java, backend/src/main/java/com/darass/darass/comment/dto/CommentCreateRequest.java, backend/src/main/java/com/darass/darass/comment/service/CommentService.java, backend/src/main/java/com/darass/darass/user/domain/User.java, backend/src/main/java/com/darass/darass/user/dto/UserResponse.java, backend/src/main/java/com/darass/darass/websocket/config/WebSocketChatConfig.java, backend/src/main/java/com/darass/darass/websocket/domain/AlarmMessageMachine.java, backend/src/main/java/com/darass/darass/websocket/domain/AlarmMessageType.java, backend/src/main/java/com/darass/darass/websocket/domain/CommentAlarmMessage.java, backend/src/test/java/com/darass/darass/comment/acceptance/CommentAcceptanceTest.java, backend/src/test/java/com/darass/darass/comment/service/CommentServiceTest.java
=> 실시간 댓글 알림 기능을 구현한다. 

backend/build.gradle, backend/src/main/java/com/darass/darass/comment/controller/CommentController.java, backend/src/main/java/com/darass/darass/comment/dto/CommentCreateRequest.java, backend/src/main/java/com/darass/darass/comment/service/CommentService.java, backend/src/main/java/com/darass/darass/user/domain/User.java, backend/src/main/java/com/darass/darass/user/dto/UserResponse.java, backend/src/main/java/com/darass/darass/websocket/config/WebSocketChatConfig.java, backend/src/main/java/com/darass/darass/websocket/domain/AlarmMessageMachine.java, backend/src/main/java/com/darass/darass/websocket/domain/AlarmMessageType.java, backend/src/main/java/com/darass/darass/websocket/domain/CommentAlarmMessage.java, backend/src/test/java/com/darass/darass/comment/acceptance/CommentAcceptanceTest.java, backend/src/test/java/com/darass/darass/comment/service/CommentServiceTest.java
=> 실시간 댓글 알림 기능을 구현한다.

README.md
=> [FE][공통]README에 프론트엔드 아키텍처를 추가한다.

README.md
=> [FE][공통] README 프론트엔드 아키텍처 업데이트

backend/src/main/java/com/darass/commentalarm/domain/CommentAlarm.java, backend/src/main/java/com/darass/commentalarm/domain/CommentAlarmMachine.java, backend/src/main/java/com/darass/commentalarm/service/CommentAlarmService.java
=> 웹 소켓으로 보낼 알람 데이터를 json으로 변환할때 문한 루프가 발생하는 버그를 해결한다. 

backend/src/main/java/com/darass/comment/domain/Comment.java, backend/src/main/java/com/darass/comment/service/CommentService.java, backend/src/main/java/com/darass/commentalarm/domain/CommentAlarm.java, backend/src/main/java/com/darass/commentalarm/domain/CommentAlarmMachine.java, backend/src/main/java/com/darass/commentalarm/dto/CommentAlarmResponse.java, backend/src/main/resources/db/migration/V20210928143035__add_receiver.sql, backend/src/test/java/com/darass/comment/acceptance/CommentAcceptanceTest.java, backend/src/test/java/com/darass/comment/service/CommentServiceTest.java, backend/src/test/java/com/darass/commentalarm/controller/CommentAlarmControllerTest.java, backend/src/test/java/com/darass/user/controller/UserAcceptanceTest.java, backend/src/test/resources/testdb/migration/V20210928143035__add_receiver.sql
=> 알람 엔티티에 seder와 receiver를 구분해서 포함한다.

backend/src/main/java/com/darass/commentalarm/controller/CommentAlarmController.java, backend/src/main/java/com/darass/commentalarm/domain/CommentAlarm.java, backend/src/main/java/com/darass/commentalarm/domain/CommentAlarmMachine.java, backend/src/main/java/com/darass/commentalarm/dto/CommentAlarmRequest.java, backend/src/main/java/com/darass/commentalarm/dto/CommentAlarmResponse.java, backend/src/main/java/com/darass/commentalarm/repository/CommentAlarmRepository.java, backend/src/main/java/com/darass/commentalarm/service/CommentAlarmService.java, backend/src/main/java/com/darass/common/domain/BaseTimeEntity.java, backend/src/test/java/com/darass/commentalarm/controller/CommentAlarmControllerTest.java, backend/src/test/java/com/darass/commentalarm/repository/CommentAlarmRepositoryTest.java, backend/src/test/java/com/darass/commentalarm/service/CommentAlarmServiceTest.java
=> 댓글 알람 데이터에 id, 생성일자 데이터를 추가한다. 

backend/src/main/java/com/darass/commentalarm/controller/CommentAlarmController.java, backend/src/main/java/com/darass/commentalarm/repository/CommentAlarmRepository.java, backend/src/main/java/com/darass/commentalarm/service/CommentAlarmService.java, backend/src/test/java/com/darass/commentalarm/controller/CommentAlarmControllerTest.java, backend/src/test/java/com/darass/commentalarm/repository/CommentAlarmRepositoryTest.java, backend/src/test/java/com/darass/commentalarm/service/CommentAlarmServiceTest.java
=> 알람 데이터 조회 버그를 수정한다.

backend/src/main/java/com/darass/comment/domain/Comment.java, backend/src/main/java/com/darass/comment/service/CommentService.java, backend/src/test/java/com/darass/comment/service/CommentServiceTest.java
=> 댓글 알람 전송 기준을 변경한다.

backend/src/main/java/com/darass/comment/domain/Comment.java, backend/src/main/java/com/darass/comment/service/CommentService.java, backend/src/test/java/com/darass/comment/service/CommentServiceTest.java
=> 댓글 알람 전송 기준을 변경한다. 

frontend/deploy-script/src/index.ts, frontend/manage/src/components/atoms/Alarm/index.tsx, frontend/manage/src/components/atoms/Alarm/styles.ts, frontend/manage/src/components/atoms/Modal/styles.ts, frontend/manage/src/components/pages/Statistics/styles.ts, frontend/manage/src/constants/styles/css.ts, frontend/manage/src/hooks/api/token/useToken.ts, frontend/reply-module/src/components/atoms/Alarm/index.tsx, frontend/reply-module/src/components/atoms/Alarm/styles.ts, frontend/reply-module/src/components/molecules/FullScreenModal/AlarmModal/index.tsx, frontend/reply-module/src/components/molecules/FullScreenModal/ConfirmModal/index.tsx, frontend/reply-module/src/components/molecules/FullScreenModal/LikingUsersModal/index.tsx, frontend/reply-module/src/components/molecules/FullScreenModal/index.tsx, frontend/reply-module/src/hooks/api/token/useToken.ts
Bearer 토큰이 제거되지 않아서 발생했음.
+ 댓글모듈에서 alert이 커스텀 UI alert으로 띄우도록 수정됨
=> [FE][댓글모듈] 로그아웃 후 댓글입력 시, 로그인이 되어있는 것처럼 동작하는 이슈 수정

backend/src/main/java/com/darass/config/datasource/CustomDataSourceConfig.java
=> [BE] DB 레플리케이션 패키지 설정 관련 버그를 해결한다.

backend/build.gradle, backend/src/main/java/com/darass/comment/dto/CommentCreateRequest.java, backend/src/main/java/com/darass/commentalarm/domain/CommentAlarmMachine.java, backend/src/main/java/com/darass/config/WebSocketConfig.java, backend/src/main/java/com/darass/websocket/config/WebSocketConfig.java, backend/src/test/java/com/darass/WebSocketTestConfig.java, backend/src/test/java/com/darass/comment/domain/CommentAlarmMachineTest.java, backend/src/test/java/com/darass/comment/domain/StubMessageChannel.java, backend/src/test/java/com/darass/comment/service/CommentAlarmReceiveTest.java, backend/src/test/java/com/darass/darass/SpringContainerTest.java
=> [BE] 실시간 알림 기능 테스트 코드를 구현한다. 

backend/build.gradle, backend/src/main/java/com/darass/comment/dto/CommentCreateRequest.java, backend/src/main/java/com/darass/commentalarm/domain/CommentAlarmMachine.java, backend/src/main/java/com/darass/config/WebSocketConfig.java, backend/src/main/java/com/darass/websocket/config/WebSocketConfig.java, backend/src/test/java/com/darass/WebSocketTestConfig.java, backend/src/test/java/com/darass/comment/domain/CommentAlarmMachineTest.java, backend/src/test/java/com/darass/comment/domain/StubMessageChannel.java, backend/src/test/java/com/darass/comment/service/CommentAlarmReceiveTest.java, backend/src/test/java/com/darass/darass/SpringContainerTest.java
=> [BE] 실시간 알림 기능 테스트 코드를 구현한다.

frontend/manage/package.json, frontend/manage/src/components/pages/ScriptPublishing/index.tsx, frontend/manage/yarn.lock
darass-react의 prop이 변경되어도 리렌더링되지 않아, 기존 UI가 유지되는 현상 수정
고객사 babble에서 제보받음
https://github.com/zereight/darass-react/commit/49d80fe774494f78acd98c3ceaa016d59cbc437c
=> [FE][관리자페이지] darass-react props 바뀌면 리렌더링되도록 수정

frontend/reply-module/webpack.config.js
webpack.config.js에
```js
optimization: {
splitChunks: {
chunks: "all"
}
}
```
위 코드 설정하였음.
변경전
변경후
=> [FE][댓글모듈] 중복된 번들 최적화

backend/src/main/java/com/darass/config/WebSocketConfig.java
=> [BE][댓글 알림] 내부 메시지큐 사용하도록 변경

backend/Dockerfile-Migration, backend/docker-compose.yml, backend/src/main/java/com/darass/config/WebSocketConfig.java
=> [BE] 마이그레이션용 설정 파일 추가 (#798)
